#editor theme
theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
color-modes = true
auto-format = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
max-wrap = 100
